//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiddenFileCleaner.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HiddenFileCleaner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   選択されたファイルを削除します。
        ///
        ///削除されたファイルはごみ箱に入ります。
        ///ただし、ネットワーク上のファイルは直ちに削除されます。
        ///続行しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogDeleteFile {
            get {
                return ResourceManager.GetString("DialogDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダーを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogSelect {
            get {
                return ResourceManager.GetString("DialogSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダーが指定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderEmpty {
            get {
                return ResourceManager.GetString("FolderEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したフォルダーが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderNotFound {
            get {
                return ResourceManager.GetString("FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リストに何も表示されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListEmpty {
            get {
                return ResourceManager.GetString("ListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除を中止しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusDelAbort {
            get {
                return ResourceManager.GetString("StatusDelAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusDelComplete {
            get {
                return ResourceManager.GetString("StatusDelComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除中 ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusDelProgress {
            get {
                return ResourceManager.GetString("StatusDelProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索を中止しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusFindAbort {
            get {
                return ResourceManager.GetString("StatusFindAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   項目が見つかりました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusFindComplete {
            get {
                return ResourceManager.GetString("StatusFindComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索中： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusFindProgress {
            get {
                return ResourceManager.GetString("StatusFindProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   準備完了。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
    }
}
